### ISSUE TITLE
Home URL incorrect

### ISSUE THREAD

**Issue by jeubanks** [akbooer/openLuup#6] opened 2018-02-13 15:43 UTC
Not sure if this more ALTUI problem or not.  However when clicking on the Home link it tries to add the port onto the BASE URL

http://192.168.254.29:3480/:3480/data_request?id=lr_ALTUI_Handler&command=home

**Comment by akbooer** [comment] 2018-02-13 17:10
Thanks for reporting that.

Which versions of openLuup and AltUI?

There have been a number of security changes recently, and they need to be kept in step.  At the same time, it’s quite possible I’ve screwed up somewhere!

AK

**Comment by akbooer** [comment] 2018-02-26 17:48
I've not been able to reproduce this.  The latest master update (18.2.26) has had significant changes handling port 3480 (because of recent Vera access changes.)  I'm assuming that this has gone away, so will close this issue unless you tell me otherwise.

**Comment by jeubanks** [comment] 2018-02-26 18:22
I would say close for now and if the issue comes back I'll report again.

**Closed as completed** 2018-02-26 20:27 UTC
